# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishMovieApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Director_name', models.CharField(max_length=50)),
                ('Hero_name', models.CharField(max_length=50)),
                ('Heroin_name', models.CharField(max_length=50)),
                ('Producer_name', models.CharField(max_length=50)),
                ('Release_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HindiMovieApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Director_name', models.CharField(max_length=50)),
                ('Hero_name', models.CharField(max_length=50)),
                ('Heroin_name', models.CharField(max_length=50)),
                ('Producer_name', models.CharField(max_length=50)),
                ('Release_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TeluguMovieApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Director_name', models.CharField(max_length=50)),
                ('Hero_name', models.CharField(max_length=50)),
                ('Heroin_name', models.CharField(max_length=50)),
                ('Producer_name', models.CharField(max_length=50)),
                ('Release_dt', models.DateTimeField()),
            ],
        ),
    ]
